# Generated by Django 5.1.1 on 2024-09-14 05:04

import django.db.models.deletion
import model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=model_utils.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(default=model_utils.aware_utcnow, editable=False)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('farmer', 'Farmer')], default='buyer', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('farm_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(default=model_utils.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.user')),
            ],
        ),
    ]
