# Generated by Django 5.1.1 on 2024-09-18 15:27

import contracts.models
import model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(default=model_utils.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=model_utils.aware_utcnow)),
                ('end_date', models.DateTimeField(default=contracts.models._default_contract_end_date)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('delivery_terms', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('cod', 'Cash on delivery'), ('credit', 'Credit card'), ('debit', 'Debit card')], default='upi', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('terms_and_conditions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
