# Generated by Django 5.1.1 on 2024-09-14 05:04

import django.db.models.deletion
import model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(default=model_utils.generate_id, max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(default=model_utils.aware_utcnow)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('delivery_terms', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('cod', 'Cash on delivery'), ('credit', 'Credit card'), ('debit', 'Debit card')], default='upi', max_length=10)),
                ('created_on', models.DateTimeField(default=model_utils.aware_utcnow, editable=False)),
                ('buyer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_contracts', to='users.user')),
                ('farmer', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_contracts', to='users.user')),
            ],
        ),
    ]
